-- Fidelidad repo↔prod (13-ago-2026): la DATA del resolver interior (workstream de despacho, F1 frente
-- tarifario 06-ago). Capturada de prod el 13-ago (information_schema + jsonb_agg + pg_indexes).
-- YA APLICADA en prod — NO re-aplicar allá. Idempotente. Se ordena ANTES de
-- 20260813180000_resolver_tarifa_v2_fn.sql para que un ambiente fresco tenga la tabla al crear la función.
--
-- Piezas: (1) tabla `lugares_interior` (63 filas: 9 provincias + 3 comarcas SIN servicio + ciudades/pueblos
-- con alias) — el diccionario del camino interior de resolver_tarifa_v2; (2) check de `zonas_entrega.metodo`
-- ampliado con 'servientrega_sucursal'/'servientrega_domicilio' (el del repo los rechazaba); (3) filas
-- 'INT Sucursal' ($6) e 'INT Domicilio' ($9) en zonas_entrega; (4) store_facts `itbms_rate` (0.07) y
-- `envio_gratis_umbral_usd` (300) — los lee resolver_tarifa_v2 para tarifa_con_itbms y envío gratis.

-- ================= 1) lugares_interior =================
create table if not exists public.lugares_interior (
  id           bigint generated by default as identity primary key,
  provincia    text not null,
  lugar        text not null,
  tipo         text not null,
  alias        text,
  con_servicio boolean not null default true,
  plazo        text,
  nota         text,
  updated_at   timestamptz not null default now(),
  unique (provincia, lugar)
);

alter table public.lugares_interior enable row level security;
grant select, insert, update, delete on public.lugares_interior to service_role;
grant usage, select on sequence public.lugares_interior_id_seq to service_role;

insert into public.lugares_interior (id, provincia, lugar, tipo, alias, con_servicio, plazo, nota, updated_at) values
  (1,'Bocas del Toro','Bocas del Toro','provincia','bocas',true,'De 3 a 5 días hábiles',null,'2026-08-06 21:50:39.0022+00'),
  (2,'Chiriquí','Chiriquí','provincia',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (3,'Coclé','Coclé','provincia',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (4,'Colón','Colón (provincia)','provincia','provincia de colon',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (5,'Darién','Darién','provincia',null,true,'De 3 a 5 días hábiles',null,'2026-08-06 21:50:39.0022+00'),
  (6,'Herrera','Herrera','provincia','provincia de herrera',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (7,'Los Santos','Los Santos','provincia',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (8,'Veraguas','Veraguas','provincia',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (9,'Panamá Oeste','Panamá Oeste','provincia',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (10,'Guna Yala','Comarca Guna Yala','comarca','guna yala, kuna yala, san blas',false,null,'Sin cobertura de entrega; un asesor coordina retiro en la sucursal Servientrega más cercana','2026-08-06 21:50:39.0022+00'),
  (11,'Emberá-Wounaan','Comarca Emberá-Wounaan','comarca','embera, embera wounaan',false,null,'Sin cobertura de entrega; un asesor coordina retiro en la sucursal Servientrega más cercana','2026-08-06 21:50:39.0022+00'),
  (12,'Ngäbe-Buglé','Comarca Ngäbe-Buglé','comarca','ngabe bugle, ngobe bugle, comarca ngabe',false,null,'Sin cobertura de entrega; un asesor coordina retiro en la sucursal Servientrega más cercana','2026-08-06 21:50:39.0022+00'),
  (13,'Bocas del Toro','Changuinola','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (14,'Bocas del Toro','Chiriquí Grande','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (15,'Bocas del Toro','Isla Colón','ciudad','bocas town, isla bocas',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (16,'Bocas del Toro','Almirante','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (17,'Chiriquí','David','ciudad','san pablo viejo, san mateo david',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (18,'Chiriquí','Boquete','ciudad','alto boquete',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (19,'Chiriquí','Volcán','ciudad','tierras altas',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (20,'Chiriquí','Puerto Armuelles','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (21,'Chiriquí','Dolega','ciudad','los algarrobos',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (22,'Chiriquí','Bugaba','ciudad','la concepcion',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (23,'Chiriquí','Gualaca','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (24,'Chiriquí','Las Lajas','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (25,'Chiriquí','Boquerón','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (26,'Chiriquí','Renacimiento','ciudad','rio sereno',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (27,'Coclé','Penonomé','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (28,'Coclé','Aguadulce','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (29,'Coclé','Natá','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (30,'Coclé','Antón','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (31,'Coclé','El Valle de Antón','ciudad','el valle',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (32,'Coclé','La Pintada','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (33,'Coclé','Río Hato','ciudad','farallon',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (34,'Colón','Colón (ciudad)','ciudad','colon, zona libre, cristobal, cuatro altos',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (35,'Colón','Sabanitas','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (36,'Colón','Cativá','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (37,'Colón','Portobelo','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (38,'Colón','Buena Vista','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (39,'Darién','La Palma','ciudad','la palma darien',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (40,'Darién','Metetí','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (41,'Darién','Yaviza','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (42,'Herrera','Chitré','ciudad','monagrillo',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (43,'Herrera','Parita','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (44,'Herrera','Pesé','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (45,'Herrera','Ocú','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (46,'Los Santos','Las Tablas','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (47,'Los Santos','Guararé','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (48,'Los Santos','Pedasí','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (49,'Los Santos','La Villa de Los Santos','ciudad','la villa',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (50,'Los Santos','Macaracas','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (51,'Los Santos','Tonosí','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (52,'Veraguas','Santiago','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (53,'Veraguas','Soná','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (54,'Veraguas','Atalaya','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (55,'Veraguas','Santa Fe','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (56,'Panamá Oeste','La Chorrera','ciudad','chorrera, el hatillo, puerto caimito',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (57,'Panamá Oeste','Arraiján','ciudad','nuevo chorrillo, vista alegre arraijan, vacamonte',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (58,'Panamá Oeste','Capira','ciudad','villa rosario',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (59,'Panamá Oeste','Chame','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (60,'Panamá Oeste','San Carlos','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (61,'Panamá Oeste','Coronado','ciudad',null,true,null,null,'2026-08-06 21:50:39.0022+00'),
  (62,'Panamá Oeste','Nueva Gorgona','ciudad','gorgona',true,null,null,'2026-08-06 21:50:39.0022+00'),
  (63,'Panamá','Tortí','ciudad','ipeti, chepo torti',true,null,'Panamá Este profundo; hoy el diccionario metro lo captura como Z4a — corregir en F1.2','2026-08-06 21:50:39.0022+00')
on conflict (provincia, lugar) do nothing;

-- La secuencia de la identity debe quedar DESPUÉS del máximo insertado (los ids fueron explícitos).
select setval(pg_get_serial_sequence('public.lugares_interior','id'), (select max(id) from public.lugares_interior));

-- ================= 2) check de metodo ampliado =================
-- El check del repo (20260706180000) permitía propia/servientrega/retiro_agente_verde/asesor; prod suma
-- los 2 métodos del interior. (Verificar contra prod: select pg_get_constraintdef — pendiente de captura;
-- se infiere porque las filas INT existen allá con estos valores.)
alter table public.zonas_entrega drop constraint if exists zonas_entrega_metodo_check;
alter table public.zonas_entrega add  constraint zonas_entrega_metodo_check
  check (metodo in ('propia','servientrega','retiro_agente_verde','asesor','servientrega_sucursal','servientrega_domicilio'));

-- ================= 3) zonas INT =================
insert into public.zonas_entrega (zona, descripcion, tarifa_base_usd, metodo, plazo, observaciones, puntos_retiro, updated_at) values
  ('INT Sucursal','Interior del país — retiro en sucursal/agente Servientrega',6,'servientrega_sucursal',
   'Al día hábil siguiente (Bocas del Toro y Darién: de 3 a 5 días hábiles). El cliente retira con su cédula en la agencia que elija.',
   'Tarifa nacional a sucursal. F1 frente tarifario 2026-08-06.',null,'2026-08-06 21:50:39.0022+00'),
  ('INT Domicilio','Interior del país — entrega puerta a puerta vía Servientrega',9,'servientrega_domicilio',
   'Al día hábil siguiente (Bocas del Toro y Darién: de 3 a 5 días hábiles).',
   'Tarifa nacional puerta a puerta. F1 frente tarifario 2026-08-06.',null,'2026-08-06 21:50:39.0022+00')
on conflict (zona) do update set
  descripcion=excluded.descripcion, tarifa_base_usd=excluded.tarifa_base_usd, metodo=excluded.metodo,
  plazo=excluded.plazo, observaciones=excluded.observaciones, puntos_retiro=excluded.puntos_retiro,
  updated_at=excluded.updated_at;

-- ================= 4) store_facts =================
insert into public.store_facts (key, value) values
  ('itbms_rate','0.07'),
  ('envio_gratis_umbral_usd','300')
on conflict (key) do update set value=excluded.value, updated_at=now();

-- Verificación:
--   select count(*) from public.lugares_interior;                       -- 63
--   select zona, tarifa_base_usd, metodo from public.zonas_entrega where zona like 'INT%'; -- 6/9
--   select public.resolver_tarifa_v2('david')->>'estado';               -- 'ok' ambito interior
